### ISSUE TITLE
Cannot get metadata of build right after creation but before completion

### ISSUE THREAD

**Issue by victorbadila** [googleapis/nodejs-cloudbuild#113]
#### Environment details

  - OS: Ubuntu 18
  - Node.js version: 10.16.0
  - npm version: 6.14.2
  - `@google-cloud/cloudbuild` version: 1.5.0

#### Steps to reproduce

  1. I need to get metadata details of a cloud build run (such as cloud build id) right after the creation, the sample only shows a basic example of creating a build and waiting for it to finish before being able to inspect the object. From the typescript definitions alone it's not clear how you can get access to cloud build id or such after its creation without. See code below
  2. 
```
import { CloudBuildClient } from '@google-cloud/cloudbuild';

const gcb = new CloudBuildClient();
const [resp] = await gcb.runBuildTrigger({
    projectId: 'something',
    triggerId: 'something',
    source: {
      projectId: 'something',
      tagName: 'something',
    },
  });

  // I need to get cloud build id from "resp", yet nothing in the typescript definitions suggest how this is possible.

  const [build] = await resp.promise();
  // I can get metadata easily from "build", but this is after the build has finished, too late for my purposes
```

Thanks,
Victor

**Comment by AndyClausen** [comment]
Any progress on this? I need it as well

**Comment by AndyClausen** [comment]
Soo.. Anything? It seems like this is a bug. It can't be right that you're not meant to be able to get any information about the build you just created until the build is finished (which can take a long time).

**Comment by donmccasland** [comment]
I'll take a look into this.

**Comment by dinagraves** [comment]
Hi!  You can either print the metadata from the build response, or you can use the method `checkRunBuildTriggerProgress`

```
 // Imports the Google Cloud client library
  const {CloudBuildClient} = require('@google-cloud/cloudbuild');

  // Creates a client
  const cb = new CloudBuildClient();

  // Starts a build against the branch provided.
  const [resp] = await cb.runBuildTrigger({
    projectId,
    triggerId,
    source: {
      projectId,
      dir: './',
      branchName,
    },
  });

  // Prints the Build Info
  console.log(resp.metadata.build)

  // Checks the progress
  const progress = await cb.checkRunBuildTriggerProgress(resp.name)
  console.log(progress.result);
  console.log(progress.done);
  console.log(progress.metadata);

  const [build] = await resp.promise();
  console.log(build)
```
