### ISSUE TITLE
502:Bad Gateway error when running runBuildTrigger

### ISSUE THREAD

**Issue by Nushio** [googleapis/nodejs-cloudbuild#119]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-cloudbuild/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Google Cloud Functions
  - Node.js version: 10
  - npm version: 6.14.5
  - `@google-cloud/cloudbuild` version: 1.5.0

#### Steps to reproduce

  1. const cb = new CloudBuildClient();
  2. cb.runBuildTrigger({
      projectId,
      triggerId,
      source: {
        projectId,
        dir: "./",
        branchName,
      },
    },(callback) => { 
      console.log(callback);
    });

It was working fine but late Monday, June 1st, something must've changed. 
We're (inconsistently but around 90% of the time) an UNAVAILABLE: 502:Bad Gateway error on the callback. 

Manually triggering the Build via the Cloud Console Dashboard works fine, but I'm not sure how to debug this app to get to the root of the problem.

**Comment by aslattery** [comment]
Experiencing this as well starting today:

```
{
  details: "502:Bad Gateway",
  metadata: {
    internalRepr: {} 
    options: {}
  },
  code: 14
}
```

**Comment by bcoe** [comment]
@Nushio @aslattery this is most likely an issue with the upstream API, not the client library.

I suggest opening an issue [here](https://issuetracker.google.com/issues/new?component=190802&template=0) on the public issue tracker for Cloud Build 👍

**Comment by bappr** [comment]
Yeah confirmed it's not related to the client library.
I am getting the same since yesterday with the go client.

**Comment by Disturbing** [comment]
I opened an issue on the public issue tracker for cloud build: https://issuetracker.google.com/issues/158130392

Referencing this ticket and the other ticket in the go client. I think this is a p0 bug, as have been unable to use cloud build for 48 hours which is detrimental to a production environment.

Please help us resolve this soon.

**Comment by Nushio** [comment]
Looks like it's been fixed upstream. 

https://issuetracker.google.com/issues/158130392
