### ISSUE TITLE
Documentation: Mocking/Stubbing certain functions requires stubbing parts of `google-gax`

### ISSUE THREAD

**Issue by isand3r** [googleapis/nodejs-cloudbuild#127]
**Is your feature request related to a problem? Please describe.**

Recently when writing some integration tests for my code I needed to stub the `createBuild` function. To do this effectively I also needed to stub the `OperationsClient` that is returned for long-running operations since that is then used to check the result of the request.

After combing through the source code for this library I figured out that the operations client comes from the `google-gax` dependency. 

**Describe the solution you'd like**

I think it would be great to document some examples of how to mock/stub this library (when using something like `sinon`) just to make it easier for folks to know how to test around this library and its dependency on gax/grpc. I'd be happy to contribute some of my own examples.

**Comment by bcoe** [comment]
@isand3r this is an interesting idea. As these libraries are largely auto generated, I wonder how we would document this in  general sense, such that folks actually discover the docs.

CC: @alexander-fenster

**Comment by alexander-fenster** [comment]
Are the auto-generated tests in `test/gapic*.ts` useful for doing what you want? In particular, this piece

https://github.com/googleapis/nodejs-cloudbuild/blob/master/test/gapic_cloud_build_v1.ts#L55-L69

and this is how we use it:

https://github.com/googleapis/nodejs-cloudbuild/blob/master/test/gapic_cloud_build_v1.ts#L1366

**Comment by isand3r** [comment]
ah interesting - thanks for the links, I hadn't seen those. I will check that out

**Comment by ace-n** [comment]
Hi folks,

I'm going to go ahead and close this issue out, since it seems like it's been resolved.

@isand3r please reopen this issue if I'm mistaken. Thanks! 😃
