### ISSUE TITLE
Support usage in Deno with ESM

### ISSUE THREAD

**Issue by jthegedus** [googleapis/nodejs-cloudbuild#152]
**Is your feature request related to a problem? Please describe.**

I want to use this module in Deno however due to the `package.json` listing `"browser": "src/browser.js",` which is expected to be an ESM module and is unavailable Deno fails to import.

 **Describe the solution you'd like**

Support ESM bundles properly

 **Describe alternatives you've considered**

I have tried importing the compiled module from UNPKG at https://www.unpkg.com/browse/@google-cloud/cloudbuild@2.0.3/ however Deno fails to resolve the exports here as well.

**Comment by alexander-fenster** [comment]
Hi @jthegedus,

Unfortunately it won't work with Deno right now (neither `@grpc/grpc-js` nor `protobufjs` are currently compatible with Deno, and both of them are our dependencies). We are thinking of how we can make it work but I cannot give you any ETA at this moment.
