### ISSUE TITLE
How to use authentication passing credentials using code.

### ISSUE THREAD

**Issue by pvhieuit** [googleapis/nodejs-cloudbuild#168]
Hi guy,

I see [HERE](https://cloud.google.com/docs/authentication/production#passing_code)
```javascript
// Imports the Google Cloud client library.
const {Storage} = require('@google-cloud/storage');

// Instantiates a client. Explicitly use service account credentials by
// specifying the private key file. All clients in google-cloud-node have this
// helper, see https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/docs/authentication.md
// const projectId = 'project-id'
// const keyFilename = '/path/to/keyfile.json'
const storage = new Storage({projectId, keyFilename});

// Makes an authenticated API request.
async function listBuckets() {
  try {
    const [buckets] = await storage.getBuckets();

    console.log('Buckets:');
    buckets.forEach((bucket) => {
      console.log(bucket.name);
    });
  } catch (err) {
    console.error('ERROR:', err);
  }
}
listBuckets();
```

With [CloudBuildClient Document](https://googleapis.dev/nodejs/cloudbuild/latest/v1.CloudBuildClient.html)
![image](https://user-images.githubusercontent.com/18276928/94762574-4de80980-03d2-11eb-9f0b-1339b2d7851b.png)

When I use this for my code:
![image](https://user-images.githubusercontent.com/18276928/94762679-999ab300-03d2-11eb-8784-4fde9fa218d3.png)

I has error
![image](https://user-images.githubusercontent.com/18276928/94762793-d9fa3100-03d2-11eb-8f7e-410a2485a70e.png)

But when i use *google-auth-library* => It's work.
![image](https://user-images.githubusercontent.com/18276928/94762861-0150fe00-03d3-11eb-992b-ab09577d7977.png)

Please help!!!

**Comment by bcoe** [comment]
@pvhieuit I believe you should be able to pass in an auth instance like this:

```js
const authClient = auth.fromJSON(keys)
const client = new CloudBuild({
  auth: authClient
})
```

☝️ does this approach work for you?

**Comment by pvhieuit** [comment]
@bcoe thank you for help, but it not working.

![image](https://user-images.githubusercontent.com/18276928/94881640-31aaa200-0490-11eb-9ba1-82296417aee1.png)

**Comment by dinagraves** [comment]
Where are you running the code?  Depending on the environment, you can use the default authorization of the caller.  If you don't specify auth, it uses the default.  For instance, this works for me when I'm running locally:

```
  // Imports the Google Cloud client library
  const {CloudBuildClient} = require('@google-cloud/cloudbuild');

  // Creates a client
  const cb = new CloudBuildClient();

  const request = {
    projectId
  }

  const result = await cb.listBuildTriggers(request)
  console.info(result)
```

If this doesn't work, you can try running `gcloud auth application-default login` ([info here](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login)) and then try again.


If you want to explicitly pass credentials through, you can use a service account key like this:

  ```
/  // Imports the Google Cloud client library
  const {CloudBuildClient} = require('@google-cloud/cloudbuild');

  client_options = {"keyFilename": "cloudbuildkey.json"}

  // Creates a client
  const cb = new CloudBuildClient(client_options)

  const request = {
    projectId
  }

  const result = await cb.listBuildTriggers(request)
  console.info(result)
```

Make sure your service account has permission to use the Cloud Build API.  I gave mine the `Cloud Build Service Agent` role.  

You can see more about authentication options [here](https://github.com/googleapis/gax-nodejs/blob/master/client-libraries.md#authentication-options).
