### ISSUE TITLE
Create a build trigger connected to a GitHub repository through the API

### ISSUE THREAD

**Issue by Shudrum** [googleapis/nodejs-cloudbuild#195]
Hello,

We are currently trying to develop an infrastructure with Google Cloud.

One of the problem we are trying to solve is to avoid repeating 100 times some basic CI/CD configurations for our microservices.

So I try to create build triggers through the API and I hurt a problem that I understand, but cannot solve:

```text
UnhandledPromiseRejectionWarning: Error: 9 FAILED_PRECONDITION: Repository mapping does not exist.
Please visit https://console.cloud.google.com/cloud-build/triggers/connect?project=21725486103
to connect a repository to your project.
```

My double checks:
- The GitHub's Cloud Build app is properly installed.
- The GitHub's Cloud Build app is properly configured for all repositories.
- Google Cloud Run is properly connected to GitHub and works well when a trigger is created manually.
- I can't even create a trigger on an already connect repository that already have a trigger.

Here is my request done with the Node.js client:

```js
const [resp] = await cloudBuild.createBuildTrigger({
  projectId: 'super-top-secret',
  trigger: {
    name: 'test-automation',
    github: {
      installationId: 0123456789,
      owner: 'our-not-so-secret-company',
      repo: 'test-nodejs-ci',
      push: {
        branch: '.*',
      },
    }
  },
});
```

Maybe I missed something? My fear is that is simply not possible.

Maybe a problem with the service account used for the API call ?

Can you help me?

Thank you!

**Comment by dinagraves** [comment]
Hi Julien,

I'm afraid that each repository has to be connected to the project in which you're trying to create the trigger.  Unfortunately, there isn't a way to programmatically connect to third party repositories.  https://cloud.google.com/build/docs/automating-builds/create-manage-triggers#connect_repo. 

Once the repository is connected, you'll be able to create the trigger with this command.  

I'm sorry for the inconvenience and for the slow response.

Best Regards,
Dina
