### ISSUE TITLE
Possibility to submit docker build

### ISSUE THREAD

**Issue by bayerlse** [googleapis/nodejs-cloudbuild#204]
Hey there.

Is there any way to achieve something like:

https://cloud.google.com/build/docs/building/build-containers?hl=en#use-dockerfile

So to build via dockerfile?

Couldn't find anything like that in the docs.

Thanks,

Sebi

**Comment by bayerlse** [comment]
If I try to deploy an uploaded gzipped tar (***.tar.gz) from cloud storage via:

```ts
const cb = new CloudBuildClient();
 await cb.createBuild({
   build: {
   id: `k8s-build-${this.commonConfig.tag}`,
      source: {
          storageSource: {
             bucket: this.serviceConfig.bucketName,
             object: this.imageTar
           }
        },
        tags: [this.commonConfig.tag],
        name: `eu.gcr.io/${this.commonConfig.projectId}/${this.commonConfig.repoName}`
    },
    projectId: this.commonConfig.projectId
});

```

 I get following error: `Cannot read property 'decode' of null`
 
 Any help here?

**Comment by dinagraves** [comment]
Hi Sebastian,

I don't think you can create a build with the client library without defining the steps.  An easy solution is to create one step that does a Docker build.  Here is an example in YAML:  https://github.com/GoogleCloudPlatform/cloud-build-samples/blob/main/run-example-builddeploy/cloudbuild.yaml#L18

I hope that helps!
-Dina

**Comment by bfan1256** [comment]
Does this also work if we want to reference local files similar to the example found [here](https://cloud.google.com/build/docs/building/build-containers?hl=en#json_1), such that we're able to do something like

```js
const cb = new CloudBuildClient();
await cb.createBuild({
   build: {
   id: `some-build`,
   projectId: 'YOUR_PROJECT_ID,
   source: { "what do I put in here?" }
    "steps": [
      {
          "name": "gcr.io/cloud-builders/docker",
          "args": [
            "build",
            "-t",
            "gcr.io/PROJECT_ID/IMAGE_NAME", "."
           ]
       }
     ]
});
