### ISSUE TITLE
Unable to create build with custom pool

### ISSUE THREAD

**Issue by michaeleekk** [googleapis/nodejs-cloudbuild#300]
I used the sample code to try triggering a cloud build from a config file. Things worked when without the worker pool parameter. I got a worker pool not found error. I could send build to the worker pool with cli but just not nodejs. I actually tried the REST API and Python SDK but also didn't work.

```
(node:631727) UnhandledPromiseRejectionWarning: Error: 5 NOT_FOUND: workerpool not found: "projects/<project id>/workerPools/<worker pool name>"
    at Object.callErrorFromStatus (/home/michael/project1/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/michael/project1/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
    at Object.onReceiveStatus (/home/michael/project1/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/home/michael/project1/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /home/michael/project1/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

#### Environment details

  - OS: Ubuntu 21.04
  - Node.js version: v12.21.0
  - npm version: 7.5.2
  - `@google-cloud/cloudbuild` version: 2.6.0

#### Steps to reproduce

```js
import json

import google.auth
from google.cloud.devtools import cloudbuild_v1

def quickstart():
    """Create and execute a simple Google Cloud Build configuration,
    print the in-progress status and print the completed status."""

    # Authorize the client with Google defaults
    credentials, project_id = google.auth.default()
    client = cloudbuild_v1.services.cloud_build.CloudBuildClient()

    build = cloudbuild_v1.Build()

    # The following build steps will output "hello world"
    # For more information on build configuration, see
    # https://cloud.google.com/build/docs/configuring-builds/create-basic-configuration
    j = json.loads(open('cloudbuild.json').read())
    build.steps = j['steps']
    build.substitutions = j['substitutions']
    build.images = j['images']
    build.options = {"pool": {"name":j['workerPool']}}
    # build.timeout = 3000 # j['timeout']

    operation = client.create_build(project_id='<project id>', build=build)
    # Print the in-progress operation
    print("IN PROGRESS:")
    print(operation.metadata)

    result = operation.result()
    # Print the completed status
    print("RESULT:", result.status)
# [END cloudbuild_quickstart]


if __name__ == "__main__":
    quickstart()
```

**Comment by ace-n** [comment]
Hi @michaeleekk and thanks for the issue. I tried to reproduce this myself but was unable to.

Can you paste a copy of your `cloudbuild.json` file here so we can reproduce this? (If there are secrets there, **please replace them with dummy values** in your paste.)

Thanks!

**Comment by mpmartinez-etsy** [comment]
good morning @ace-n  - i actually have an open support case about this exact issue. Can i provide an example JS file that in my experience replicates this issue? I can replicate this with the following:

#!/usr/bin/env node
"use strict";

const CloudBuild = require("@google-cloud/cloudbuild");

const projectId = "<an-existent-project>";
const client = new CloudBuild.CloudBuildClient();
const privatePool = "<an-existent-private-pool>";
const build = {
    options: {
        pool: {
            name: privatePool,
        },
    },
    steps: [
        {
            args: ["/bin/echo", "hello"],
            id: "example",
            name: "ubuntu",
        },],};

client.createBuild({ build, projectId });

I can provide the specific case number so that you can see the exact project name and resource name if that's necessary, please let me know.

**Comment by ok-devalias** [comment]
The client libraries are hitting the global api endpoint by default, so for regional resources like this, you'll need to provide additional `clientOptions` when building the client.

NodeJS
```
// To build the client, use region + service path as an override api endpoint.
const opts = {apiEndpoint: "us-central1-cloudbuild.googleapis.com"}
const client = new CloudBuild.CloudBuildClient(opts);
```

Python
```
... previous imports
from google.api_core.client_options import ClientOptions

client_options = ClientOptions(api_endpoint="us-central1-cloudbuild.googleapis.com")
client = cloudbuild_v1.services.cloud_build.CloudBuildClient(client_options=client_options)
```

These types of options are described in the gax-nodejs README: https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md#service-options

**Comment by mpmartinez-etsy** [comment]
for anyone else who stumbles across this, this 100% solves my problem - thank you @ok-devalias !
